---

- name: install metricbeat on webservers
  hosts: webservers
  become: true
  tasks:

    - name: Download metricbeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Copy config file
      copy:
        src: /etc/ansible/files/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
        remote_src: no

    - name: enable system
      command: metricbeat modules enable docker

    - name: metricbeat setup
      command: metricbeat setup

    - name: start service
      command: service metricbeat start
